mod administration;
pub mod commands;
pub mod config;
pub mod models;
mod operational;
mod payroll_seed;
mod scanner;
pub mod secrets;
pub mod sql_backend;
pub mod storage;
pub mod sync;
mod time_policy;
pub mod turso;

pub mod academic;
pub mod attendance_dashboard;
pub mod attendance_ledger;
pub mod class_attendance;
pub mod grades;
pub mod license;
pub mod payroll;
pub mod portability;
pub mod teaching_journal;
pub mod wa_notification;
pub mod wa_sender;
pub use config::DesktopState;
